<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageDescription>Sample Theorems for Sudoku and River Crossing problems.</PackageDescription>
    <PackageTags>Z3; LINQ; Solver; SMT; Examples; Sudoku; Bart De Smet</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Z3.Linq\Z3.Linq.csproj" />
  </ItemGroup>

</Project>
