<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>LINQ bindings for Z3, a satisfiability modulo theories solver from Microsoft Research. Based on a proof of concept from Bart De Smet.</Description>
    <PackageTags>Z3; LINQ; Solver; SMT; Bart De Smet</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MiaPlaza.ExpressionUtils" />
    <PackageReference Include="Microsoft.Z3" />
  </ItemGroup>

</Project>
